[project]
name = "process-aquarium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.3.3",
    "psutil>=7.1.0",
    "pygame>=2.6.1",
    "pytest>=8.4.2",
]
