[project]
name = "process-aquarium"
version = "0.1.0"
description = "Visualize processes as fish in an aquarium"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "psutil>=7.1.0",
    "pygame-ce>=2.5.2",
    "pytest>=8.4.2",
]
